### ISSUE TITLE
Error in SE ver. 01_203_022

### ISSUE THREAD

**Issue by Gusko-SVK** [austinvaness/LcdImagePlugin#1]
Hi,
thanks for the great work on your plugins and loader.
Recent update of SE did some changes to LCD screens (mostly removing deprecated stuff as far as I know), resulting in error with LcdImagePlugin:

2023-09-01 21:45:14.670 - Thread:   1 ->  [PluginLoader] [Info] Downloading https://github.com/austinvaness/LcdImagePlugin/archive/239bbff92f7dd4a7c842ad210d562e82ec9d9bfd.zip
2023-09-01 21:45:15.855 - Thread:   1 ->  [PluginLoader] [Error] CS1061: 'MyTextPanel' does not contain a definition for 'SelectedRotationIndex' and no accessible extension method 'SelectedRotationIndex' accepting a first argument of type 'MyTextPanel' could be found (are you missing a using directive or an assembly reference?) in file:
LcdImagePlugin-239bbff92f7dd4a7c842ad210d562e82ec9d9bfd/LcdImagePlugin/Patch_CreateTerminalControls.cs (111,34)
2023-09-01 21:45:15.860 - Thread:   1 ->  [PluginLoader] [Error] Failed to load austinvaness/LcdImagePlugin|Image to LCD because of an error: System.Exception: Compilation failed!
   at avaness.PluginLoader.Compiler.RoslynCompiler.Compile(String assemblyName, Byte[]& symbols)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(String commit, String assemblyName, Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)
   
Looking forward to fix.
If you need any further info, please let me know.

Best regards,
Gusko

**Comment by austinvaness** [comment]
This should be fixed in the latest version
